FROM python:3.10 

WORKDIR /app

#COPY .env /app
COPY requirements.txt /app

RUN pip install --upgrade pip && pip install -r /app/requirements.txt

EXPOSE 8000

# COPY ./ /app

CMD ["python", "api.py"]